// <auto-generated />
namespace Bulgarian_Apparel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedhotpropertyandstocktoproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedhotpropertyandstocktoproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201711130925576_added hot property and stock to products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
