// <auto-generated />
namespace Bulgarian_Apparel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SecondseedItem2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondseedItem2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031748340_Second seed Item2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
