// <auto-generated />
namespace Bulgarian_Apparel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PurpleShirtSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurpleShirtSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201711141435211_PurpleShirtSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
