// <auto-generated />
namespace Bulgarian_Apparel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderitemnowhasorderid2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderitemnowhasorderid2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101632441_order item now has order id 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
